<div class="content">
    <div class="content-main">
        <p class="main-title">Мозырь - Экспресс</p>
        <!--p class="main-text">Маршрутка Мозырь-Гомель</p-->
        <div class="d-flex justify-content-center">
            <p class="main-tel">8 (</p>
            <ul class="align-bottom main-list">
                <li><a href="tel:8 029 539 98 77"><img class="main-list" src="/img/logo-mts.jpg"> 029</a></li>
                <li><a href="tel:8 044 539 98 77"><img class="main-list" src="/img/logo-velcom.jpg"> 044</a></li>
                <li><a href="tel:8 025 539 98 77"><img class="main-list" src="/img/logo-life.jpg"> 025</a></li>
            </ul>
            <p class="main-tel">) <a href="tel: 539 98 77"> 539-98-77</a></p>
        </div>
    </div>
    <h1>Page Not Found!</h1>
    <div class="content-warning">
        <div class="container">
            <p class="warning-title">Внимание!</p>
            <p class="warning-content">
                При возниковении проблем <a class="modal-link" data-toggle="modal" href="#phoneCall" aria-expanded="false" aria-controls="phoneCall">позвоните</a> оператору.<br>
                Вам помогут забронировать место или решить возникшую проблему.
            </p>
        </div>
    </div>
</div>