<div class="content-form" id="app">
    <form-block token="<?php echo $this->security->getToken() ?>" token-key="<?php echo $this->security->getTokenKey() ?>"></form-block>
</div>
<div class="content-android">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <span class="android-text align-bottom">Скачай бесплатно наши приложения</span>
            </div>
            <div class="col-3 col-lg-2">
                <a  href="https://play.google.com/store/apps/details?id=ru.avtsystem.mozyr">
                    <img id="android-img" class="store-image" src="/img/googleplay.png" alt="Google Play">
                </a>
            </div>
            <div class="col-3 col-lg-2">
                <a  href="https://itunes.apple.com/us/app/%D0%BC%D0%BE%D0%B7%D1%8B%D1%80%D1%8C-%D1%8D%D0%BA%D1%81%D0%BF%D1%80%D0%B5%D1%81%D1%81/id1449465346?l=ru&ls=1&mt=8">
                    <img id="apple-img" class="store-image" src="/img/appstore.png" alt="App Store">
                </a>
            </div>
            <div class="d-none d-lg-block col-2">
                <img class="smart-image" src="/img/smartphone.png" alt="Smartphone">
            </div>
        </div>
    </div>
</div>
<div class="content-questions container">
    <p class="section-title">Частые вопросы</p>
    <a data-toggle="collapse" href="#question0" aria-expanded="false" aria-controls="question0">- Сколько времени в пути?</a>
    <div class="collapse" id="question0">
        <div class="card card-body">
            Дорога из Мозыря в Гомель занимает 2 часа. Время движения в пути зависит от времени года, дорожных и погодных условий, а также форс-мажорных ситуаций.
        </div>
    </div>
    <a data-toggle="collapse" href="#question1" aria-expanded="false" aria-controls="question1">- Обязательно ли подтверждать заказ?</a>
    <div class="collapse" id="question1">
        <div class="card card-body">
            Нет, не обязательно, достаточно просто быть на связи. Но в случае, если Вы не можете выезать в назначеное время, необходимо перезвонить и отменить бронь.
        </div>
    </div>
    <a data-toggle="collapse" href="#question2" aria-expanded="false" aria-controls="question2">- Выдаются ли документы командировочным?</a>
    <div class="collapse" id="question2">
        <div class="card card-body">
            При оплате проезда, вам будут выданы документы, подтверждающие факт принятия денег, а также сопроводительные документы.
        </div>
    </div>
    <a data-toggle="collapse" href="#question3" aria-expanded="false" aria-controls="question3">- По какому маршруту идет сбор пассажиров по Мозырю при поездке в Гомель?</a>
    <div class="collapse" id="question3">
        <div class="card card-body">
            Сбор пассажиров производится по 14 маршруту в Мозыре.
        </div>
    </div>
    <a data-toggle="collapse" href="#question4" aria-expanded="false" aria-controls="question4">- Можно ли передать посылку через вашу маршрутку?</a>
    <div class="collapse" id="question4">
        <div class="card card-body">
            Решение взять или нет передачу принимает непосредственно водитель, т.к. наша компания не занимается доставкой грузов. Вы можете узнать телефон водителя, который отправляется в нужное Вам время в диспетчерской и договориться с ним лично.
        </div>
    </div>
</div>